# dbt/models/marts/schema.yml
version: 2

models:
  - name: dim_customers
    description: "Customer Dimension Table"
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
  - name: dim_products
    description: "Product Dimension Table"
    columns:
      - name: product_key
        tests: [not_null, unique]
  - name: dim_sellers
    description: "sellers Dimension Table"
    columns:
      - name: seller_key
        tests: [not_null, unique]
  - name: dim_geolocation
    description: "geo Dimension Table"
    columns:
      - name: zip_key
        tests: [not_null, unique]  # tests: [not_null, unique]

  - name: fact_orders
    description: "Order fact table, centered on the customer dimension"
    columns:
      - name: order_key
        tests:
          - not_null
          - unique
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
      - name: order_status
        tests:
          - accepted_values:
              values: "{{ var('order_status_valid') }}"
